services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - rabbit_net

  producer:
    build: ${PRODUCER_DIR}
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      AUTH_URL: ${AUTH_URL}
    ports:
      - "${PRODUCER_PORT}:8081"
    networks:
      - rabbit_net

  consumer:
    build: ${CONSUMER_DIR}
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
    ports:
      - "${CONSUMER_PORT}:8080"
    networks:
      - rabbit_net

networks:
  rabbit_net:
    driver: bridge
